### ISSUE TITLE
font load Error in MacOS intel 13.4

### ISSUE THREAD

**Issue by zhengying** [yariker/xfontgen#2]
<img width="793" alt="Screenshot 2024-05-17 at 00 03 53" src="https://github.com/yariker/xfontgen/assets/1042545/f8bcf36e-ac46-4f97-98fb-d2213be2cbb5">

**Comment by yariker** [comment]
@zhengying Please check out [v1.2.0](https://github.com/yariker/xfontgen/releases/v1.2.0). I believe this should now be fixed.

**Comment by zhengying** [comment]
great!, I tested it.  it's OK
