### ISSUE TITLE
CSC : error CS7065: Error building Win32 resources -- Icon stream is not in the expected format.

### ISSUE THREAD

**Issue by zhengying** [yariker/xfontgen#4]
The Icon.ico file is incorrect, so an error showed `CSC : error CS7065: Error building Win32 resources -- Icon stream is not in the expected format.` when I build the project on macOS. 

 Replacing the correct Icon.ico file can fix it.

**Comment by yariker** [comment]
@zhengying make sure you have [Git LFS](https://git-lfs.com/) installed, then do `git lfs pull`.

**Comment by zhengying** [comment]
Interesting.  but why?
I think this just because your Icon.ico not correct binary file. It's OK after I replaced a correct one

**Comment by yariker** [comment]
It's a rule of thumb that binary files should go to LFS to keep the repo size down. It's mostly install-and-forget once you have it.

**Comment by zhengying** [comment]
great.
but I just tried `git lfs pull` to pull the binary, but the result is the same, I think the problem should be invalid Icon.ico file.

**Comment by yariker** [comment]
Same with `git lfs fetch --all`?

**Comment by zhengying** [comment]
> Same with `git lfs fetch --all`?

Same. 
ico file not correct format.

**Comment by yariker** [comment]
It is in the correct format in the repo as you can see yourself on Github, so you'd have to figure out what's wrong with your Git LFS setup.

**Comment by zhengying** [comment]
> It is in the correct format in the repo as you can see yourself on Github, so you'd have to figure out what's wrong with your Git LFS setup.

Yes, I found the ico file in GitHub is correct, the size is normal, my local file is only 133 Byte, I tried to delete it and then checkout. and
`git lfs fetch --all ` and all kind of operation, is still not working, I think maybe it's a bug of Git or Git LFS.
